sudo: false
language: python
python:
- '3.5'
before_install:
- pip install -r requirements.txt
- pip install -e .
script: pytest -m "not compiled" --cov=pythonwhat
after_success: codecov --token=$CODECOV_TOKEN
deploy:
  provider: pypi
  user: datacamp
  password:
    secure: PVJrnm2rLmrKkNdcTM4yqfe2v7+dTwu936FCUtDLPIC6inL4Neky9Zs2GpFv9lD9IQ0a7jTdbFp/TzC8klzxDd7LE72YVyZcrafrWXGpXw4WwBozmTsyGLnCXAQ54urMbcwLYw3OR4oUGeoPGOxBsEiQXiPH5Yvwcm9IFuQr98/IRedwqS0udDqWmuvPYfBwK6VSoDhN+jC07B5sdoYfqKlOXkQuleSDJ2XlY8mndbgD3OCpegqcp6ysYj3v80OStJMB0sxMg92q1Ltcn6d5uIFJsYo/K2BfSPP9JANLIicU3AqDIOSinPP9mky915HSQzbqBISIXp6oPcMBcwA+Eju9h3yssAGo1MBGiGQB8Pg46wFiWfPTtceaibjJyfs1nC1SSc7AgP7kaDJhrBRh1XAOhIuyEyrQ5O++7Wvs7kCPYeDQ3VHDsNSVYaVHNP0moGImQKQn/1dKLz9C+tkP4V+GcjLnaj4FfWaAz+CqNqFbxPIJOi8KFIHqWJp/uxIKLGJVjd46vsgsTOl7YuiPQO8hWwqkYR/Vdb9vxvn15SaXI5WCESejo5sg3bI4BQhaIq/3cK00p+BKQHc66rVUezo228kLPDSRZEDfAPyVhTEgAOEVGUPkD7efFMqGhw6WbrnNze6QY2+EsLr57WLNVtJzYgwbOuKeCSxy+JhvXbA=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: datacamp/pythonwhat
  skip_upload_docs: true
